# Site Info
title:              "Taylor Gibb"
description:        "0x2b || ~0x2b thats the real question"
author_name:        "Taylor Gibb"
logo_url:           https://avatars2.githubusercontent.com/u/13660108?v=4 

# Site Settings
url:                https://taylorgibb.github.io # main url
baseurl:            ""
permalink:          /blog/:title # Post permalink
timezone:           Africa/Johannesburg
mathjax:            false  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile"]
plugins:
  - jekyll-sitemap



defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
